# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Porfolio de Schmidely Stéphane
email: schmidely.stephane@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Retrouver sur ce portfolio, l'ensemble de mes projets (web notamment).
  N'hesitez pas à visiter ma page de profil pour me contacter ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephlm2dev.github.io" # the base hostname & protocol for your site
twitter_username: Schmidely_Steph
github_username: stephlm2dev
permalink: /:categories/:title.html

# Build settings
markdown: kramdown

# Author
author:
  age: 23
  driving_licenses: Moto et Auto
  degree: M2 Informatique
  passions: Photographie, voyages ...
  name: Schmidely Stéphane
  email: schmidely.stephane@outlook.com
  github: stephlm2dev
  twitter: Schmidely_Steph
  viadeo: schmidely.stéphane
  deviantart: stephlm2dev
  repository: stephlm2dev.github.io
